### ISSUE TITLE
utf-8问题

### ISSUE THREAD

**Issue by ghost** [TISUnion/joinMOTD#5]
文件是utf-8的格式，但是还是报错
![image](https://user-images.githubusercontent.com/59270149/124703911-c2357780-df25-11eb-8167-3c1cf869576b.png)

**Comment by ghost** [comment]
哦，我好像知道了，我去试试

**Comment by ghost** [comment]
解决了，配置文件忘记改回UTF-8了awa

**Comment by alex3236** [comment]
解决了请关闭 Issue
